# Generated by Django 3.2.18 on 2023-04-30 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('breathing_problem', models.BooleanField()),
                ('fever', models.BooleanField()),
                ('dry_cough', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('runny_nose', models.BooleanField()),
                ('asthma', models.BooleanField()),
                ('chronic_lung_disease', models.BooleanField()),
                ('headache', models.BooleanField()),
                ('heart_disease', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('hypertension', models.BooleanField()),
                ('fatigue', models.BooleanField()),
                ('gastrointestinal', models.BooleanField()),
                ('abroad_travel', models.BooleanField()),
                ('contact_with_covid_patient', models.BooleanField()),
                ('attended_large_gathering', models.BooleanField()),
                ('visited_public_exposed_places', models.BooleanField()),
                ('family_working_in_public_exposed_places', models.BooleanField()),
                ('wearing_mask', models.BooleanField()),
                ('sanitization_from_market', models.BooleanField()),
                ('covid', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
