# Generated by Django 4.2.1 on 2023-05-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_symptomguideline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomguideline',
            name='id',
        ),
        migrations.AlterField(
            model_name='symptomguideline',
            name='symptom',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
